xq update (#1)
* add list CRUD commands

* update replace

* work on readme

* gh action

* work on readme

* add actions example

* actions: update rename

* update delete

* randomize self node

* randomize self node

* add error line if failed to run

* update facility code insert, delete, replace

* actions: debug

* actions: debug2

* actions: debug3

* actions: debug4

* actions: debug5

* actions: debug6

* actions: debug

* actions: debug7

* actions: debug8

* actions: debug9

* actions: debug10

* actions: load main modules

* actions: put test

* actions: load main mods

* action: update insert example

* action: update insert example2

* action: update insert example3

* action: update insert example4

* action: update insert example5

* action: update insert example6

* action: update delete example

* action: update delete example2

* action: update delete example2

* action: update replace example

* action: update rename example

* action: tidy up examples

* action: main formating

* container clean before up

* container clean before up

diff --git a/bin/xq b/bin/xq
--- a/bin/xq
+++ b/bin/xq
@@ -17,8 +17,6 @@ function help() { ## show this help	 db-exists)
   awk 'BEGIN {FS = ").*?## "}; {printf "\033[36m%-10s\033[0m %s\n", $1, $2}'
 }
 
-
-
 function ok (){
   echo -n "✔  " && echo  $1
 }
@@ -31,95 +29,19 @@ function die() {
 }
 
 # check if in project root
-grep -oP '^XQERL_HOME' .env ||  die "you are not call xq from a xQuery project root"
+
+grep -oP '^XQERL_HOME' .env &>/dev/null || die "you are not call xq from a xQuery project root"
 # check required arguments
 [[ ${#args[@]} -eq 0 ]] && help && exit
 source .env
 XQERL_IMAGE=docker.pkg.github.com/grantmacken/alpine-xqerl/xq:$GHPKG_VER
 MountAssets="type=volume,target=$XQERL_HOME/priv/static/assets,source=static-assets"
 
-function dbDomainExists() {
-  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
- docker exec xq xqerl escript bin/scripts/call.escript \
-    "xqldb_db_server"  "exists" "$resource"
- #docker exec xq xqerl escript bin/scripts/call.escript "xqldb_lib"  "filename_to_uri" "/tmp/markup.nz"
-  }
+#######################
+#  xq db CRUD commands for xqerl db
+#######################
 
-function dbItemType() {
-  docker exec xq xqerl escript bin/scripts/run.escript \
-    db-item-type.xq $1
-  }
-
-function dbGetLink() {
-  local local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
-  local collection=$(dirname $resource)
-  if [ -n "$(dbList $collection | grep -oP "^${resource}$")" ]
-    then
-    ok "resource in db: [ $resource ]"
-    docker exec xq xqerl escript bin/scripts/query.escript  "'$resource' => db:get()" 
-  else
-    die "resource NOT found in db: [ $resource ]"
-  fi
-}
-
-function dbGetItem() {
-  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
-  local itemType=$(dbItemType $resource)
-  case "$itemType" in
-    document-node)
-      docker exec xq xqerl escript bin/scripts/query.escript "'$resource' => doc() => serialize(map{'omit-xml-declaration': true() })"
-      ;;
-    array)
-     docker exec xq xqerl escript bin/scripts/query.escript \
-        "'$resource' => db:get() => serialize(map{'method': 'json' })"
-      ;;
-    map)
-      docker exec xq xqerl escript bin/scripts/query.escript \
-        "'$resource' => db:get() => serialize(map{'method': 'json' })"
-      ;;
-    *)
-      die "[ $itemType ] unknown XDM item"
-  esac
-}
-
-function dbList() {
-  local path="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
-  docker exec xq xqerl escript bin/scripts/query.escript \
-    "try { ('$path' => uri-collection()) => string-join('&#10;') } catch * {()}" 
-}
-
-function doCall() {
-  docker exec xq xqerl escript bin/scripts/call.escript \
-    "$1" "$2" "$3"
-  }
-
-function isDocAvailable() {
-  docker exec xq xqerl escript bin/scripts/query.escript \
-  "'$1' => doc-available() => string()"
-}
-
-function isAvailable() {
-  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
-  echo $resource
-  docker exec xq xqerl escript bin/scripts/query.escript \
-    "( '$resource' = ( remove( \
-        '$resource' => \
-        tokenize('/'),'$resource' => \
-        tokenize('/') => \
-        count()\
-        )\
-      ) => \
-      string-join('/')  => \
-      string() => \
-      uri-collection()\
-    ) => string()"
-}
-
-function getDoc() {
-  docker exec xq xqerl escript bin/scripts/query.escript \
-    "'$1' => doc() => serialize(map{'omit-xml-declaration': true() })"
-}
-
+# [ put {srcFile} ]  Create a db XDM item from a data src file
 function dbFilePut() {
   local base="$(echo $1 | grep -oP '^(src/data/)?\K(.+)$')"
   local srcFile="src/data/$base"
@@ -156,50 +78,7 @@ function dbFilePut() {
   fi
 }
 
-function dbDeleteItem() {
-  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
-  if "$( isDocAvailable $resource )"
-  then
-    docker exec xq xqerl escript bin/scripts/query.escript  "'$resource' => db:delete()"
-    ok "resource deleted from db: [ $resource ]"
-  else 
-    if isAvailable $resource
-      then
-      docker exec xq xqerl escript bin/scripts/query.escript  "'$resource' => db:delete()" &>/dev/null
-      ok "resource deleted from db: [ $resource ]"
-    else
-      die "resource NOT found in db: [ $resource ]"
-    fi
-  fi
-}
-
-function dbDeleteCollection() { 
- echo 'TODO'
-}
-
-function doCompile() { 
-  local base="$(echo $1 | grep -oP '^(src/(main_modules|library_modules)/)?\K(.+)$')"
-  if [ -e src/main_modules/$base ] ;then  
-   docker cp src/main_modules/$base xq:/usr/local/xqerl/code/src/$base 
-  else 
-    if [ -e src/library_modules/$base ] ; then
-      docker cp src/library_modules/$base xq:/usr/local/xqerl/code/src/$base 
-    else die "[ $1 ] unknown file"
-    fi
-  fi
-  docker exec xq xqerl escript bin/scripts/compile.escript  "code/src/$base"
-}
-
-function doRun() { 
-  local base="$(echo $1 | grep -oP '^(src/main_modules/)?\K(.+)$')"
-  local srcFile="src/main_modules/$base"
-  [ -e $srcFile ] || die "[ $srcFile ] unknown file"
-  docker cp $srcFile xq:/usr/local/xqerl/code/src/$base 
-  docker exec xq xqerl escript bin/scripts/run.escript  $1 "$2"
-}
-
-#xqerl_update:add(Ctx, {put, link, Filename, DB, Name}).
-
+# [ link ] Create - a db link to a binary or unparsed text file
 function dbLink() {
   local domain=$1
   local base="$(echo $2 | grep -oP '^(src/static_assets/)?\K(.+)$')"
@@ -232,6 +111,173 @@ function dbLink() {
   esac
 }
 
+# utility for Read actions
+function dbItemType() {
+  docker exec xq xqerl escript bin/scripts/run.escript \
+    db-item-type.xq $1
+  }
+
+# [ get ]  Read - given uri get db XDM item
+function dbGetItem() {
+  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
+  local itemType=$(dbItemType $resource)
+  case "$itemType" in
+    document-node)
+      docker exec xq xqerl escript bin/scripts/query.escript \
+       "try{('${resource}' => doc()) => serialize(map{'omit-xml-declaration': true() })} catch * {()}"
+      ;;
+    array)
+     docker exec xq xqerl escript bin/scripts/query.escript \
+        "'$resource' => db:get() => serialize(map{'method': 'json' })"
+      ;;
+    map)
+      docker exec xq xqerl escript bin/scripts/query.escript \
+        "'$resource' => db:get() => serialize(map{'method': 'json' })"
+      ;;
+    *)
+      die "[ $itemType ] unknown XDM item"
+  esac
+}
+
+# [ get ]  Read - given uri get db XDM item
+function dbGetItemPath() {
+  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
+  local itemType=$(dbItemType $resource)
+  case "$itemType" in
+    document-node)
+      local xpath="${args[2]}"
+      echo ${xpath} | grep -oP '^/(.+)$' &>/dev/null || die 'arg [ xpath ] must be a xpath expression'
+      docker exec xq xqerl escript bin/scripts/query.escript \
+        "try{('${resource}' => doc())${xpath} => serialize(map{'omit-xml-declaration': true() })} catch * {()}"
+      ;;
+    array) #TODO
+     docker exec xq xqerl escript bin/scripts/query.escript \
+        "'$resource' => db:get() => serialize(map{'method': 'json' })"
+      ;;
+    map) # TODO
+      docker exec xq xqerl escript bin/scripts/query.escript \
+        "'$resource' => db:get() => serialize(map{'method': 'json' })"
+      ;;
+    *)
+      die "[ $itemType ] unknown XDM item"
+  esac
+}
+
+# TODO  [ get ]  Read - db link 
+function dbGetLink() {
+  local local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
+  local collection=$(dirname $resource)
+  if [ -n "$(dbList $collection | grep -oP "^${resource}$")" ]
+    then
+    ok "resource in db: [ $resource ]"
+    docker exec xq xqerl escript bin/scripts/query.escript  "'$resource' => db:get()" 
+  else
+    die "resource NOT found in db: [ $resource ]"
+  fi
+}
+
+# [ list ] Read - list db uri collections
+function dbList() {
+  local path="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
+  docker exec xq xqerl escript bin/scripts/query.escript \
+    "try { ('$path' => uri-collection()) => string-join('&#10;') } catch * {()}" 
+}
+
+# [ available ] Read - is db item available
+function isAvailable() {
+  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
+  docker exec xq xqerl escript bin/scripts/query.escript \
+    "( '$resource' = ( remove( \
+        '$resource' => \
+        tokenize('/'),'$resource' => \
+        tokenize('/') => \
+        count()\
+        )\
+      ) => \
+      string-join('/')  => \
+      string() => \
+      uri-collection()\
+    ) => string()"
+}
+
+function dbUpdate() {
+  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
+  if isDocAvailable $resource &> /dev/null
+  then
+    docker exec xq xqerl escript bin/scripts/query.escript \
+      "'$resource' => doc() => serialize()"
+    else die "xQuery update facilty only available for XML documents[ $ext ]"
+  fi
+}
+
+# [ delete ] Delete - delete a single XDM or link item
+function dbDeleteItem() {
+  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
+  if "$( isDocAvailable $resource )"
+  then
+    docker exec xq xqerl escript bin/scripts/query.escript  "'$resource' => db:delete()"
+    ok "resource deleted from db: [ $resource ]"
+  else 
+    if isAvailable $resource
+      then
+      docker exec xq xqerl escript bin/scripts/query.escript  "'$resource' => db:delete()" &>/dev/null
+      ok "resource deleted from db: [ $resource ]"
+    else
+      die "resource NOT found in db: [ $resource ]"
+    fi
+  fi
+}
+
+function dbDomainExists() {
+  local resource="http://$(echo $1 | grep -oP '^(http://)?\K(.+)$')"
+ docker exec xq xqerl escript bin/scripts/call.escript \
+    "xqldb_db_server"  "exists" "$resource"
+ #docker exec xq xqerl escript bin/scripts/call.escript "xqldb_lib"  "filename_to_uri" "/tmp/markup.nz"
+  }
+
+function doCall() {
+  docker exec xq xqerl escript bin/scripts/call.escript \
+    "$1" "$2" "$3"
+  }
+# utility: available XML docs
+function isDocAvailable() {
+  docker exec xq xqerl escript bin/scripts/query.escript \
+  "try {'$1' => doc-available() => string()} catch * { 'false' }"
+}
+
+function getDoc() {
+  docker exec xq xqerl escript bin/scripts/query.escript \
+    "'$1' => doc() => serialize(map{'omit-xml-declaration': true() })"
+}
+
+function dbDeleteCollection() { 
+ echo 'TODO'
+}
+
+function doCompile() { 
+  local base="$(echo $1 | grep -oP '^(src/(main_modules|library_modules)/)?\K(.+)$')"
+  if [ -e src/main_modules/$base ] ;then  
+   docker cp src/main_modules/$base xq:/usr/local/xqerl/code/src/$base 
+  else 
+    if [ -e src/library_modules/$base ] ; then
+      docker cp src/library_modules/$base xq:/usr/local/xqerl/code/src/$base 
+    else die "[ $1 ] unknown file"
+    fi
+  fi
+  docker exec xq xqerl escript bin/scripts/compile.escript  "code/src/$base"
+}
+
+function doRun() { 
+  local base="$(echo $1 | grep -oP '^(src/main_modules/)?\K(.+)$')"
+  local srcFile="src/main_modules/$base"
+  [ -e $srcFile ] || die "[ $srcFile ] unknown file"
+  docker cp $srcFile xq:/usr/local/xqerl/code/src/$base 
+  docker exec xq xqerl escript bin/scripts/run.escript  $1 "$2"
+}
+
+#xqerl_update:add(Ctx, {put, link, Filename, DB, Name}).
+
+
 function doRec() {
   local uri="$1"
   local xpath="$2"
@@ -248,9 +294,81 @@ function doLookup() {
     "try{('${uri}' => json-doc())${lookup} } catch * {()}" 
 }
 
+# "rename" "node" TargetExpr "as" NewNameExpr
+function dbUpdateRename() {
+  local resource="http://$(echo ${1} | grep -oP '^(http://)?\K(.+)$')"
+  echo "${args[3]}" | grep -oP '^(node)$' &>/dev/null || die 'arg [ node ] must be included '
+  echo "${args[4]}" | grep -oP '^/(.+)$' &>/dev/null || die 'arg [ target ] must be a xpath expression'
+  echo "${args[5]}" | grep -oP '^(as)$' &>/dev/null || die 'arg [ as ] must be included'
+  docker exec xq xqerl escript bin/scripts/query.escript \
+"declare %updating function local:update(){
+ for \$var in ('${resource}' => doc())${args[4]}
+ return 
+  rename node (\$var) as ${args[6]}
+}; 
+try{(local:update(),'ok')} catch * { 'error: failed'}"
+}
+
+# xq update example.com/examples/works.xml replace node '//employee[1]/hours[1]' with '<hours>25</hours>'
+function dbUpdateReplace() {
+  local resource="http://$(echo ${1} | grep -oP '^(http://)?\K(.+)$')"
+  echo "${args[3]}" | grep -oP '^(node|value of node)$' &>/dev/null || die 'arg must be [ node | value of node ] '
+  echo "${args[4]}" | grep -oP '^/(.+)$' &>/dev/null || die 'arg [ target ] must be a xpath expression'
+  echo "${args[5]}" | grep -oP '^(with)$' &>/dev/null || die 'arg [ with ] must be included'
+docker exec xq xqerl escript bin/scripts/query.escript \
+    "declare %updating function local:update(){
+      for \$var in ('${resource}' => doc())${args[4]}
+        return replace ${args[3]} \$var with ${args[6]}
+      };
+    try{(local:update(),'ok')  } catch * {false()}"
+}
+
+# DeleteExpr  "delete" ("node" | "nodes") TargetExpr
+# xq update example.com/examples/works.xml delete node /works/employee[1]/hours[1]'
+function dbUpdateDelete() {
+  local resource="http://$(echo ${1} | grep -oP '^(http://)?\K(.+)$')"
+  echo "${args[3]}" | grep -oP '^(node|nodes)$' &>/dev/null || die 'arg must be [ node | nodes ] '
+  echo "${args[4]}" | grep -oP '^/(.+)$' &>/dev/null || die 'arg [ target ] must be a xpath expression'
+  # echo ' - xQuery updating expression ' 
+  # echo "> delete ${args[3]} ('${resource}' => doc())${args[4]}"
+  docker exec xq xqerl escript bin/scripts/query.escript \
+    "declare %updating function local:update(){
+      for \$var in ('${resource}' => doc())${args[4]}
+        return delete ${args[3]} \$var 
+      };
+    try{(local:update(),'ok')  } catch * {false()}"
+  }
+
+# xq update example.com/examples/works.xml insert node '<hours>25</hours>' after '/works[1]/employee[1]/hours[1]'
+function dbUpdateInsert() {
+  local resource="http://$(echo ${1} | grep -oP '^(http://)?\K(.+)$')"
+  echo "${args[3]}" | grep -oP '^(node|nodes)$' &>/dev/null || die 'arg must be [ node | nodes ] '
+  #local qualifier="${args[3]}"
+  #local items="${args[4]}" # should be parsable?
+  echo "${args[5]}" | grep -oP '^(into|before|last|after|as (first|last) into)$' &>/dev/null || \
+    die '{where} one of [ into | before | last | as first into | as last into  ]'
+  #local where="${args[5]}"
+  echo "${args[6]}" | grep -oP '^/(.+)$' &>/dev/null || die 'arg [ target ] must be a xpath expression'
+  #local xpath="${args[6]}"
+  #echo ' - xQuery updating expression ' 
+  #echo "> insert $qualifier $items $where ('${resource}' => doc())${xpath}"
+docker exec xq xqerl escript bin/scripts/query.escript \
+"declare %updating function local:update(){
+  for \$var in ('${resource}' => doc())${args[6]}
+    return insert ${args[3]} ${args[4]} ${args[5]} \$var 
+  };
+try{(local:update(),'ok')  } catch * {false()}"
+}
+
 case "${args[0]}" in
   put) ## {domain}/{path} create xdm item from file. example: `xq put example.com/usecase/employees.xml`
-    dbFilePut ${args[1]}
+    case "${#args[@]}" in
+      2) 
+        dbFilePut ${args[1]}
+        ;;
+      *)
+        die '- xq put {path} : incorrect number of args'
+    esac
     ;;
   list) ## {domain/path} list resources. example: `xq list example.com/usecase`
     dbList ${args[1]}
@@ -259,19 +377,96 @@ case "${args[0]}" in
     isAvailable "${args[1]}"
     ;;
   get) ## {domain}/{path} retrieve and serialize resource . example: `xq get example.com/usecase/employees.xml`
-   res="${args[1]}"
-   base=$(basename -- "$res")
-   ext="${base##*.}"
-  #  local regItem="^(xml|array|map)$"
-  if echo ${ext} | grep -oP '^(svgz)$' &>/dev/null
+    res="${args[1]}"
+    base=$(basename -- "$res")
+    ext="${base##*.}"
+    #  local regItem="^(xml|array|map)$"
+    if echo ${ext} | grep -oP '^(svgz)$' &>/dev/null
     then dbGetLink ${res}
-  elif echo ${ext} | grep -oP '^(cmark|article|xml|array|map)$' &>/dev/null
-    then dbGetItem ${res}
-  else die "can not handle extension [ $ext ]"
-  fi
+    elif echo ${ext} | grep -oP '^(cmark|article|xml|array|map)$' &>/dev/null
+    then
+      case "${#args[@]}" in
+        2) 
+          dbGetItem "${args[1]}"
+          ;;
+        3)
+          dbGetItemPath "${args[1]}"
+          ;;
+        *)
+          die ' incorrect number of args'
+      esac
+    else die "can not handle extension [ $ext ]"
+    fi
+    ;;
+  update) ## {db-uri} {xpath-expression} {update-expression} update XML db resource
+    # example
+    # this will be a updating function
+    # for $var in ('http://example.com/examples/employees.xml' => doc())/employees/employee[1]  (: selection :)
+    # return rename node ($var) as "employee1    (: update :)
+    #############################################################
+    # for $var in ('${uri}' => doc())${xpath}  (: selection :)
+    # return ${kw} ${qualifier} ($var) as {what}    (: update :)
+    # xq update 
+    # selection part: {uri} {xpath}
+    # update part: {kw} {qualifier} {what}
+    # xq update example.com/examples/employees.xml '/employees/employee[1]' rename node 'employee1'
+    resource="http://$(echo ${args[1]} | grep -oP '^(http://)?\K(.+)$')"
+    isDocAvailable "${resource}" &> /dev/null || die ' doc not available'
+    kw="${args[2]}"
+    # echo -n " - with doc ${kw} "
+    case "$kw" in
+      insert)
+       #xq update example.com/examples/works.xml insert node '<hours>60<hours>' after '//employee[1]/hours[1]'
+        case "${#args[@]}" in
+          7) 
+            dbUpdateInsert "${args[1]}"  "${args[2]}"
+            ;;
+          *)
+            die '- xq {db-uri} {keyword1} {keyword2} {items} {where} {target}  : incorrect number of args'
+        esac
+      ;;
+      delete)
+        #xq put example.com/examples/works.xml delete node  '/works[1]/employee[3]/hours[1]'
+        case "${#args[@]}" in
+          5) 
+            dbUpdateDelete "${args[1]}"  "${args[2]}"
+            ;;
+          *)
+            die '- xq {db-uri} {keyword1} {keyword2} {xpath} : incorrect number of args'
+        esac
+        ;;
+        replace)
+        # replace node location with items
+        case "${#args[@]}" in
+          7) 
+            dbUpdateReplace "${args[1]}" 
+            ;;
+          *)
+            die '- xq update {db-uri} replace {[node|nodes]} {xpath} with {items} : incorrect number of args'
+        esac
+        ;;
+      rename)
+        # rename node location as name-expression
+        case "${#args[@]}" in
+          7) 
+            dbUpdateRename "${args[1]}" 
+            ;;
+          *)
+            die '- xq update {db-uri} rename node {xpath} as {name} : incorrect number of args'
+        esac
+        ;;
+        *)
+        die 'xq update {uri} [ insert | delete | replace | rename ] '
+    esac
     ;;
   delete) ## {domain}/{path} delete resource from db. example: `xq delete example.com/static-assets/icons/article.svg`
-   dbDeleteItem "${args[1]}"
+      case "${#args[@]}" in
+        2) 
+          dbDeleteItem "${args[1]}"
+          ;;
+        *)
+          die '- xq delete {db-uri} : incorrect number of args'
+      esac
    ;;
   #domain) # {domain} check if domain exists in db. example: `xq db-exists example.com` 
   #  dbDomainExists ${args[1]}
